### PR TITLE
Removed roundabout oneway check

### PR DESCRIPTION
**Pull request by Rdclare75**
Found to be redundant as roundabout implies oneway = yes @taylorsmock

### CODE REVIEW

**Comment by vespax** [comment]
Depending on the road direction, you would want to check roundabouts for oneways.

-Aaron.

**Comment by Rdclare75** [comment]
To clarify, in OSM the tag roundabout implies oneway, and therefore the is no reason to add the tag.

**Comment by Rdclare75** [comment]
@taylorsmock still need this pushed

**Comment by taylorsmock** [comment]
I know. The biggest argument _for_ removing it is that Osmose flags roundabouts with oneway tags.

**Comment by taylorsmock** [comment]
Merged in 5fae7d21911fd347af3f552d9a29254648194c9a

**Pull request closed without merging**
